### PR TITLE
Move png icons into an asset catalog

### PR DESCRIPTION
**Pull request by anongitter**
Use of an asset catalog to store png icons instead of a folder to make
it way easier to read in the Xcode project.

### CODE REVIEW

**Comment by Eitot** [comment]
Does this not break the images in the help menu?

**Comment by anongitter** [comment]
I don't know because I am unable to build it, there is an issue in "download" (Command /usr/bin/make failed with exit code 2).

**Comment by bumblebritches57** [comment]
Your issue is almost certainly to do with code signing. Disable that and it should build.

**Comment by pornel** [comment]
Image files are used by help files. Also last time I checked letting Xcode manage images caused them to be converted to poorly compressed TIFFs (these are small files, but still I can't ship poorly compressed files! :))

**Pull request closed without merging**
